### ISSUE TITLE
Can't get the samples to work

### ISSUE THREAD

**Issue by walseb** [skyway/skyway-webrtc-gateway#20]
Hi! I'm following [this](https://qiita.com/nakakura/items/a99c468c56db2a92b32f) guide. It recommends me to run the samples `media_callee.rb` and `media_caller.rb`. This is what I did:
1. I Installed [the windows binary of this project](https://github.com/skyway/skyway-webrtc-gateway/blob/master/README-en.md#download) and then ran it
2. I downloaded the source code of this project
3. I did `cd skyway-webrtc-gateway/samples`
4. I edited `media_callee.rb` and entered my skyway API key
5. I did `ruby.exe media_callee.rb`

The result I got was this:
```
Traceback (most recent call last):
        1: from media_callee.rb:13:in `<main>'
../skyway-webrtc-gateway/samples/util.rb:55:in `create_peer': undefined method `[]' for nil:NilClass (NoMethodError)
```

I'm running windows 10

Am I doing something wrong? I don't know any ruby and I can't find any instructions for the samples. Thanks!

**Comment by nakakura** [comment]
These codes refer to the environment variables.
https://github.com/skyway/skyway-webrtc-gateway/blob/master/samples/media_callee.rb#L3
So you need to export API_KEY.

**Comment by walseb** [comment]
I see thanks! But now I'm getting another error. I'm using [this](https://github.com/nakakura/SkyWay-WebRTC-GW-Unity-Sample/tree/master/Web) to connect to the server but after I replace `INPUT YOUR API KEY` at line 21 with my skyway key I get this error:
> The domain "null" is not registered to this API key. Please confirm your settings on the SkyWay dashboard https://webrtc.ecl.ntt.com/login.html

With the stacktrace:
```
SkyWay:  Error: The domain "null" is not registered to this API key. Please confirm your settings on the SkyWay dashboard https://webrtc.ecl.ntt.com/login.html
    at socket_Socket.<anonymous> (skyway-latest.js:17899)
    at socket_Socket.emit (skyway-latest.js:2694)
    at Socket.<anonymous> (skyway-latest.js:14385)
    at Socket../node_modules/component-emitter/index.js.Emitter.emit (skyway-latest.js:771)
    at Socket../node_modules/socket.io-client/lib/socket.js.Socket.onevent (skyway-latest.js:9979)
    at Socket../node_modules/socket.io-client/lib/socket.js.Socket.onpacket (skyway-latest.js:9937)
    at Manager.<anonymous> (skyway-latest.js:624)
    at Manager../node_modules/component-emitter/index.js.Emitter.emit (skyway-latest.js:771)
    at Manager../node_modules/socket.io-client/lib/manager.js.Manager.ondecoded (skyway-latest.js:9425)
    at Decoder.<anonymous> (skyway-latest.js:624)
error	@	skyway-latest.js:14045
(anonymous)	@	skyway-latest.js:17901
emit	@	skyway-latest.js:2694
(anonymous)	@	skyway-latest.js:14385
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/lib/socket.js.Socket.onevent	@	skyway-latest.js:9979
./node_modules/socket.io-client/lib/socket.js.Socket.onpacket	@	skyway-latest.js:9937
(anonymous)	@	skyway-latest.js:624
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/lib/manager.js.Manager.ondecoded	@	skyway-latest.js:9425
(anonymous)	@	skyway-latest.js:624
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/node_modules/socket.io-parser/index.js.Decoder.add	@	skyway-latest.js:13412
./node_modules/socket.io-client/lib/manager.js.Manager.ondata	@	skyway-latest.js:9415
(anonymous)	@	skyway-latest.js:624
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js.Socket.onPacket	@	skyway-latest.js:11164
(anonymous)	@	skyway-latest.js:10981
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js.Transport.onPacket	@	skyway-latest.js:11611
callback	@	skyway-latest.js:12523
./node_modules/engine.io-parser/lib/browser.js.exports.decodePayload	@	skyway-latest.js:1531
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js.Polling.onData	@	skyway-latest.js:12527
(anonymous)	@	skyway-latest.js:12079
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.onData	@	skyway-latest.js:12252
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.onLoad	@	skyway-latest.js:12319
xhr.onreadystatechange	@	skyway-latest.js:12205
XMLHttpRequest.send (async)		
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.create	@	skyway-latest.js:12217
Request	@	skyway-latest.js:12119
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.XHR.request	@	skyway-latest.js:12046
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.XHR.doPoll	@	skyway-latest.js:12076
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js.Polling.poll	@	skyway-latest.js:12497
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js.Polling.onData	@	skyway-latest.js:12536
(anonymous)	@	skyway-latest.js:12079
./node_modules/component-emitter/index.js.Emitter.emit	@	skyway-latest.js:771
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.onData	@	skyway-latest.js:12252
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.onLoad	@	skyway-latest.js:12319
xhr.onreadystatechange	@	skyway-latest.js:12205
XMLHttpRequest.send (async)		
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.Request.create	@	skyway-latest.js:12217
Request	@	skyway-latest.js:12119
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.XHR.request	@	skyway-latest.js:12046
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js.XHR.doPoll	@	skyway-latest.js:12076
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js.Polling.poll	@	skyway-latest.js:12497
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js.Polling.doOpen	@	skyway-latest.js:12442
./node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js.Transport.open	@	skyway-latest.js:11546
./node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js.Socket.open	@	skyway-latest.js:10953
Socket	@	skyway-latest.js:10826
Socket	@	skyway-latest.js:10733
./node_modules/socket.io-client/lib/manager.js.Manager.open.Manager.connect	@	skyway-latest.js:9306
Manager	@	skyway-latest.js:9149
Manager	@	skyway-latest.js:9117
lookup	@	skyway-latest.js:9030
start	@	skyway-latest.js:14164
async function (async)		
start	@	skyway-latest.js:14155
_initializeServerConnection	@	skyway-latest.js:17766
peer_Peer	@	skyway-latest.js:17496
(anonymous)	@	script.js:20
```

I tried adding "null" as a domain but it didn't change anything. I have also tried it in both chrome and firefox with the same result.

**Comment by walseb** [comment]
Nevermind, I just forgot to open the page through the webserver. Thanks for all the help!

**Comment by nakakura** [comment]
Sure. Glad to hear that your problem has been solved.
